- hosts: webservers #here ensure that node instance 
  become: true
  tasks:
  - name: Install HTTPD using Ansible Playbook
    package:
      name: httpd
      state: present

  - name: Start HTTPD service
    service:
      name: httpd
      state: started
      enabled: yes
                                                                                                                            