- hosts: webservers
  become: true
  vars:
   software: apache2
   fileowner: tk
   filegroup: pkadmin
   statestatus: present
  tasks:
  - name: Create group
    group:
     name: "{{ filegroup }}"
     gid: 401 #meaning group id
      
  - name: create user
    user:
     name: "{{ fileowner }}"
     state: "{{ statestatus }}"
     uid: 400      #meaning user id
     groups: "{{ filegroup }}" #meaning you have to create group first
     shell: /bin/bash

  - name: create  file
    file:
     path: /opt/webconfig.conf
     state: touch
     owner: "{{ fileowner }}" #meaning you have to create user and group first
     group: "{{ filegroup }}"

  - name: Creating folder
    file:
     path: /opt/webfile
     state: directory
     owner: "{{ fileowner }}"
     group: "{{ filegroup }}"
     # add other task to waht we have  already installing apache and doanloading some files from the intenrt
  - name: install apache2 and download the files
    apt:
     name: "{{ software }}"
     state: "{{ statestatus }}"

  - name: start the apache2 service
    service:
     name: "{{ software }}"
     state: started
     enabled: yes

 