- hosts: webservers
  become: true
  tasks:
  - name: Create group
    group:
     name: pkadmin
     gid: 401 #meaning group id
      
  - name: create user
    user:
     name: tk
     state: present
     uid: 400      #meaning user id
     groups: pkadmin #meaning you have to create group first
     shell: /bin/bash

  - name: create  file
    file:
     path: /opt/webconfig.conf
     state: touch
     owner: tk #meaning you have to create user and group first
     group: pkadmin

  - name: Creating folder
    file:
     path: /opt/webfile
     state: directory
     owner: tk 
     group: pkadmin
     # add other task to waht we have  already installing apache and doanloading some files from the intenrt
  - name: install apache2 and download the files
    apt:
     name: apache2
     state: present

  - name: start the apache2 service
    service:
     name: apache2
     state: started
     enabled: yes

 - name: Download files
   ansible.builtin.get_url:
    url: https://github.com/ShaifArfan/one-page-website-html-css-project.git
    dest: /var/www/html
    method: "get"
    remote_src: yes    # ansible needs to know that this giuy master.zip will be available on the remote machine

 - name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://github.com/ShaifArfan/one-page-website-html-css-project/archive/refs/heads/master.zip
    dest: /var/www/html
    remote_src: yes

 - name: copy the docwnloaded contents into /var/www/html
   shell: |
          cd /var/www/html && cp -r one-page-website-html-css-project-master/* /var/www/html/
 




